### ISSUE TITLE
Containerd default path for private key to decrpyt Image

### ISSUE THREAD

**Issue by vinaykagithapu** [containerd/imgcrypt#181]
This below is the containerd config in kind cluster at `/etc/containerd/config.toml`

```shell
[plugins."io.containerd.ocicrypt.v1"]
  key_model = "jwe"
  private_key_paths = ["/etc/containerd/keys/key.pem"]

[stream_processors."io.containerd.ocicrypt.decoder.v1.tar.gzip"]
  accepts = ["application/vnd.oci.image.layer.v1.tar+gzip+encrypted"]
  returns = "application/vnd.oci.image.layer.v1.tar+gzip"
  path = "/usr/local/bin/ctd-decoder"

[stream_processors."io.containerd.ocicrypt.decoder.v1.tar.zstd"]
  accepts = ["application/vnd.oci.image.layer.v1.tar+zstd+encrypted"]
  returns = "application/vnd.oci.image.layer.v1.tar+zstd"
  path = "/usr/local/bin/ctd-decoder"

[stream_processors."io.containerd.ocicrypt.decoder.v1.tar"]
  accepts = ["application/vnd.oci.image.layer.v1.tar+encrypted"]
  returns = "application/vnd.oci.image.layer.v1.tar"
  path = "/usr/local/bin/ctd-decoder"
```

Created a pod with encrypted container, but from containerd I got the below error
`Apr 23 14:01:08 kind-control-plane containerd[1786]: time="2025-04-23T14:01:08.688048958Z" level=error msg="PullImage \"docker.io/testrepo/bash:v1-encrypt\" failed" error="failed to pull and unpack image \"docker.io/testrepo/bash:v1-encrypt\": failed to extract layer sha256:a16e98724c05975ee8c40d8fe389c3481373d34ab20a1cf52ea2accc43f71f4c: call to DecryptLayer failed: missing private key needed for decryption:\n\n: unknown"`

**Comment by vinaykagithapu** [comment]
Instead of default path,  configured key path in args as below and key_mode="node"

```toml
[plugins."io.containerd.grpc.v1.cri".image_decryption]
  key_model = "node"

[stream_processors."io.containerd.ocicrypt.decoder.v1.tar.gzip"]
    accepts = ["application/vnd.oci.image.layer.v1.tar+gzip+encrypted"]
    returns = "application/vnd.oci.image.layer.v1.tar+gzip"
    path = "/usr/local/bin/ctd-decoder"
    args = ["--decryption-keys-path", "/keys"]
  [stream_processors."io.containerd.ocicrypt.decoder.v1.tar"]
    accepts = ["application/vnd.oci.image.layer.v1.tar+encrypted"]
    returns = "application/vnd.oci.image.layer.v1.tar"
    path = "/usr/local/bin/ctd-decoder"
    args = ["--decryption-keys-path", "/keys"]
```
